### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [leka-ren/project10#3]
Здравствуйте
Благодарю за проделанную работу.
К сожалению текущая реализация содержит ряд недостатков не позволяющих мне засчитать работу на данной итерации

Репозиторий:

**Нужно исправить**: отсутствуют git-теги отражающие номер версии. Создать их можно при помощи команды `git tag -a v0.0.1 -m "my first version"`
Обращаю внимание что теги по-умолчанию не публикуются при вызове команды `git push`
Для их публикации выполните команду `git push origin --tags`
Подробнее: https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8

**Нужно исправить**: README файл должен содержать номер версии (ненулевой), **ссылку на проект (github pages)** и заголовок отражающий назначение проекта.

**Можно лучше**: Добавить .gitignore.
.gitignore должен содержать правила, исключающие попадание временных и\или системных файлов в репозиторий.
 
Регулярные выражения:
Имя
**Нужно исправить**: следующие корректные имена не проходят валидацию
Ян-Ян - двойное имя (произвольное)

Email:

**Нужно исправить**: следующие корректные адреса почты не проходят валидацию
som-e@d-omains.ru - имя и домен могут содержать тире
some2@2domains.ru - имя и домен могут содержать цифры
some@some.x.com - доменное имя может содержать поддомены

**Нужно исправить**: следующие некорректные адреса почты проходят валидацию
`a@sit_te.ru` - доменное имя не может содержать спецсимволы

Номер телефона:
Негативные:
**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
+7(925 900-90-90
+7925900-90-90
+792590090-90
+7 (925) 900-90-90
+7 (925) 9009090 
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

Адрес сайта:
**Нужно исправить**: не проходят валидацию следующие корректные адреса
http://8.8.8.8:8080 - IP+порт
http://8.8.8.8:8080/page/to/deep#

**Нужно исправить**: валидацию проходят следующие некорректные адреса
`http://www.ya.` - отсутствует доменная зона

**Можно лучше**: валидацию проходят следующие некорректные адреса
`https://999.999.999.999/` (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
`https://mysite.23` (tld не может состоять из цифр) 
`http://www.google.ru///////` (в пути количество слешей подряд должно быть ограничено 1)

**Comment by zlocate** [comment]
Добрый вечер. 
Благодарю за проделанную работу. 
К сожалению, в текущей версии есть недостатки, требующие исправления.

Репозиторий:
**Можно лучше** во всех трех ветках необходимо разместить одинаковую версию приложения. Для этого основные работы рекомендую проводить в ветке `develop` а затем мерджить изменения в ветки `gh-pages` и `master`
**Нужно исправить** в файле README отсутствует ссылка на Github Pages. (https://leka-ren.github.io/project10/validation/)

Регулярные выражения:
Имя
**Нужно исправить** валидацию не проходят корректные имена состоящие из одного слова.
Пример: Денис, Сергей.
Обращаю ваше внимание что валидацию должны проходить как одинарные так и двойные имена.

**Можно лучше** задать ограничение на длину имени при помощи аттрибутов minlength и maxlength. В вашем текущем варианте на каждую часть задано минимальное ограничение по одному символу, однако т.к может быть и имя из одного слова ограничение может быть некорректным.

Email:
**Нужно исправить** в имени пользователя (части до символа @) нет ограничения на максимальную длину
`someveryveryveryveryverylongnname@mail.ru` - корректный адрес почты, однако он не проходит валидацию.
**Нужно исправить** в адресе почты также нет ограничения  и на длину доменного имени.
`name@someveryveryveryveryverylongdomain.ru` - корректный адрес почты, однако он не проходит валидацию
**Нужно исправить** доменная зона также может быть длинной. Я рекомендую вам убрать ограничение на длину сверху.
`some@yandex.academy`
Доменная зона .academy не единственная длинная доменная зона :)
**Нужно исправить** не проходят валидацию адреса почты содержащие поддомены? например `some@mail.yandex.ru`

**Можно лучше** my---mail@site.ru - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным

Адрес сайта
**Нужно исправить** валидацию не проходят следующие корректные адреса сайта

http://google.ru:98/ - доменное доменное имя + порт (со слешем на конце)
http://x.com:30 - короткое доменное имя (1 символ, является корректным) + порт
http://some.test.yandex.ru - адрес сайта содержащий поддомены
http://ya.ru:10000 - доменное имя + порт. Номер порта может быть от 1 до 65535.

**Нужно исправить** валидацию проходят следующие некорректные адреса
http://www.ya - отсутствует доменная зона (например .ru \.com и т.п)

**Comment by leka-ren** [comment]
Я поискала инфу, и нашла то, что www может быть доменным именем, и запись http://www.ya  может являться валидной, хоть и в малой степени вероятности.

**Comment by zlocate** [comment]
> Я поискала инфу, и нашла то, что www может быть доменным именем, и запись http://www.ya может являться валидной, хоть и в малой степени вероятности.
> Пример тому http://www.ru/

В общем случае вы правы. Принимается.

**Comment by zlocate** [comment]
@leka-ren отличная работа. Проблемы, отмеченные ранее успешно устранены.
После правок один кейс перестал отрабатывать корректно:
http://google.ru:/path/to/deep - данный адрес сайта некорректен, после `:` отсутствует номер порта.

**Comment by zlocate** [comment]
Добрый день. Работа принимается!
Желаю вам успехов в дальнейшем прохождении курса :)
